sudo: required
services:
  - docker
script:
  - docker pull mattkomm/cvmfs-cms
  - docker run -h dev --privileged -v $PWD:/scripts:ro mattkomm/cvmfs-cms /bin/bash -c /scripts/test/runCMSSWTest.sh
notifications:
  email:
    recipients:
      - mkomm@cern.ch
    on_success: changet
    on_failure: always


